config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
root "engarde#index"
resources :engarde
resources :miseries_misfortunes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/engarde_character.rb
# == Schema Information
#
# Table name: engarde_characters
#
#  id            :bigint           not null, primary key
#  allowance     :integer
#  birth_class   :string
#  birth_rank    :string
#  con           :integer
#  end           :integer
#  exp           :integer
#  inheritance   :integer
#  initial_funds :integer
#  ma            :integer
#  name          :string
#  position      :string
#  social_level  :integer
#  str           :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
class EngardeCharacter < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/engarde_controller.rb
class EngardeController < ApplicationController

  def index
  end

  def show
    case params[:id]
    when 'character'
      @character = RandomEngardeCharacter.new.call
    when 'companion'
      @companion = RandomEngardeCompanion.new.call
    end
  end

end

app/controllers/miseries_misfortunes_controller.rb
class MiseriesMisfortunesController < ApplicationController

  def index
    @npc = MmNpcGenerator.new.call
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engarde_helper.rb
module EngardeHelper
end

app/helpers/miseries_misfortunes_helper.rb
module MiseriesMisfortunesHelper
end

app/views/engarde/_character.html.slim
h2 Engarde New Character
div class="relative bg-blue-200 px-6 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-4"
  div#flex
    h3 #{@character.birth_rank} of a #{@character.position.titleize}
    div class="flex space-x-4"
      div Str: #{@character.str}
      div Con: #{ @character.con}
      div End: #{ @character.end}
      div Exp: #{ @character.exp}
      div MA: #{ @character.ma}
      div SL: #{ @character.social_level}
    div class="grid gap-4 grid-cols-3"
      div Initial Funds: #{ @character.initial_funds}
      div Allowance: #{ @character.allowance}
      div  Inheritance: #{ @character.inheritance}
br

app/views/engarde/_companion.html.slim
h2 Engarde New Companion
div class="relative bg-green-200 px-6 shadow-xl ring-1 ring-gray-900/5 sm:mx-auto sm:max-w-lg sm:rounded-lg sm:px-4"
  div#flex
    div
      h4 Social Level: #{ @companion.social_level}
      - if @companion.has_wealth
        p Is Wealthy
      - if @companion.has_influence
        p Is Influencial
      - if @companion.has_beauty
        p  Has Beauty
br

app/views/engarde/index.html.slim
div class="prose"
  h2 En Garde!
  div  class="block rounded-lg bg-white shadow-[0_2px_15px_-3px_rgba(0,0,0,0.07),0_10px_20px_-2px_rgba(0,0,0,0.04)] dark:bg-neutral-700"
    img  class="rounded-t-lg"  src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Map_of_Paris_by_Claes_Jansz._Visscher_-_Harold_B._Lee_Library.jpg/1280px-Map_of_Paris_by_Claes_Jansz._Visscher_-_Harold_B._Lee_Library.jpg"
  div class="p-6"
    h5 class="mb-2 text-xl font-medium leading-tight text-neutral-800 dark:text-neutral-50"  A  PlayByPost is Dead resource.
    p class="mb-4 text-base text-neutral-600 dark:text-neutral-200"
    = link_to  'New Character', engarde_path(:character), class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 m-2 rounded-full"
    = link_to  'New Companion', engarde_path(:companion), class:"bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"

app/views/engarde/show.html.slim
div class="prose"
  - if @character.present?
    =render partial: 'character'
  - if @companion.present?
    =render partial: 'companion'
  br
  = link_to  'New Character', engarde_path(:character), class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 m-2 rounded-full"
  = link_to  'New Companion', engarde_path(:companion), class:"bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Play FearlessApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
    </main>
  </body>
</html>

app/views/miseries_misfortunes/index.slim
div class="container mx-auto"
  div class="bg-cover justify-center border-2" style="background-image: url('fall_of_angels_v2.jpg')"
    div.flex.flex-col.flex-auto.prose.ml-8
      h2.text-center Miseries & Misfortunes NPC Generator
      div.text-emerald-900.font-medium.text-justify.backdrop-opacity-30.backdrop-invert.bg-white-900.border-2.pl-4
        h4.text-emerald-900 = @npc[:birth_quality]
        em = @npc[:text]
        p #{@npc[:religion]}, #{@npc[:politics]}
        p Income Source: #{@npc[:income_source]}, #{@npc[:income_range]}
        p Property: #{@npc[:property]}, Asset Value:  #{@npc[:asset_value]}
        p Wealth Rank: #{@npc[:wealth_rank]}
        p Debt: #{@npc[:debt]}
        span
          = "Obligations: #{@npc[:obligations]} "
          em = "(doesn't include Lifestyle options.)"
        - if (@npc[:dependents].length > 0)
          p Dependents:
          ul.list-disc
            - @npc[:dependents].each do |el|
              li #{el}
        - else
          p Dependents: 0
        .flex.flex-row
          strong Str: #{@npc['Str']} (#{@npc['Str_mod']})
          strong.px-4  Int: #{@npc['Int']} (#{@npc['Int_mod']})
          strong.px-4  Wis: #{@npc['Wis']} (#{@npc['Wis_mod']})
          strong.px-4  Dex: #{@npc['Dex']} (#{@npc['Dex_mod']})
          strong.px-4  Con: #{@npc['Con']} (#{@npc['Con_mod']})
          strong.px-4  Cha: #{@npc['Cha']} (#{@npc['Cha_mod']})
      p.ml-4 = link_to  "Next NPC", miseries_misfortunes_path,  class:"bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white border border-blue-500 hover:border-transparent rounded"
      //ul.list-none.text-center
        - @npc.keys.each do |key|
          li.text-emerald-900.font-medium #{key}: #{@npc[key]}